Update pre-commit to use CI base image
pika-org/pika pull request #1307
Opened 2024-11-01 07:51 UTC by aurianer

- Simplifies the pre-commit script
- Use pika-ci-base image to have the updated clang-format and cmake-format version

The previous pre-commit script supposed that we had clang-format and cmake-format installed on the system. It also supposed that we update it each time we decide to upgrade the versions.
This PR is using the docker image used in CI, pulls it if it's not available locally. The requirement here is podman, but the user can also remove podman from the pre-commit script if he prefers, the simplified commands run within podman can be run locally

2024-11-01 09:10 UTC, msimberg requested changes
Some minor comments, looks good to me otherwise.

@biddisco might want to have a look as well since I think he's also using the pre-commit hook. If there's a preference for either we can also consider having both the old and the new version as alternatives (though only option is better of course).

2024-11-01 09:10 UTC, msimberg commented on tools/pre-commit
> +checksum=$(git diff --cached --name-only | grep -E '(CMakeLists.txt|\.cmake$)' | xargs -I {} sh -c 'md5sum {}')
```suggestion
checksum=$(git diff --cached --name-only | grep -E '(^CMakeLists.txt|\.cmake)(\.in)?$' | xargs -I {} sh -c 'md5sum {}')
```
? Not 100% sure about my regex-fu.

2024-11-01 09:10 UTC, msimberg commented on tools/pre-commit
> +    bash -c "git diff --cached --name-only | grep -E '(CMakeLists.txt|\.cmake$)' | xargs cmake-format -i"
```suggestion
    bash -c "git diff --cached --name-only | grep -E '(^CMakeLists.txt|\.cmake)(\.in)?$' | xargs cmake-format -i"
```

2024-11-01 09:10 UTC, msimberg commented on tools/pre-commit
> +checksum_after_format=$(git diff --cached --name-only | grep -E '(CMakeLists.txt|\.cmake$)' | xargs -I {} sh -c 'md5sum {}')
```suggestion
checksum_after_format=$(git diff --cached --name-only | grep -E '(^ CMakeLists.txt|\.cmake)(\.in)?$' | xargs -I {} sh -c 'md5sum {}')
```

2024-11-01 09:10 UTC, msimberg commented on tools/pre-commit
>  #!/bin/bash
Do you mind changing this while you're at it?
```suggestion
#!/usr/bin/env bash
```

2024-11-01 09:10 UTC, msimberg commented on tools/pre-commit
> +podman run -w /pika/source -v=$(git rev-parse --show-toplevel):/pika/source docker.io/pikaorg/pika-ci-base:latest \
Possibly:
```suggestion
podman run -w /pika/source -v=$(git rev-parse --show-toplevel):/pika/source docker.io/pikaorg/pika-ci-base:27 \
```

It'll be right 99% of the time with `:latest` as well, but we have to update all the other `:27`s to `:28` anyway when bumping the image tag, so not the end of the world to update it here as well? On the other hand, CI will anyway reject the PR in the 1% cases. I'm fine either way.

I would maybe move the image name out into a variable though, just to make it more visible which image we're using and not having to repeat it.

2024-11-05 08:05 UTC, msimberg commented on tools/pre-commit
> +    git-clang-format -f --extensions cpp,hpp
Yep, looks like you're right. We still check for it in CI, so I don't think it's worth worrying too much about this corner case then. Manually formatting is not an improvement, so feel free to keep it this way. Please do add the CUDA extensions though.

2024-11-05 08:06 UTC, msimberg commented on tools/pre-commit
> +checksum_after_format=$(git diff --cached --name-only | grep -E '(CMakeLists.txt|\.cmake$)' | xargs -I {} sh -c 'md5sum {}')
Good point, that's fine by me.

2024-11-11 09:07 UTC, msimberg approved these changes

2024-11-11 09:08 UTC, merged

2024-11-11 12:33 UTC, biddisco commented
This is horrific - why would you require podman to be run to use a commit hook?