Clean up `version` module
pika-org/pika pull request #166
Opened 2022-03-31 14:31 UTC by aurianer

Part of #16. Removes hwloc, boost and mpi dependency in the `version` module.

2022-04-01 08:13 UTC, msimberg requested changes

2022-04-01 08:13 UTC, msimberg commented on libs/pika/version/include/pika/version.hpp
> +    PIKA_EXPORT constexpr std::uint8_t major_version();
These have to be defined inline. I suggest adding a small unit test that confirms that they can actually be used in constant expressions.

2022-04-01 08:13 UTC, msimberg commented on libs/pika/version/include/pika/version.hpp
> +    PIKA_EXPORT constexpr std::string_view tag();
Excellent idea!

2022-04-01 08:13 UTC, msimberg commented on libs/pika/version/include/pika/version.hpp
>      PIKA_EXPORT std::string copyright();
I think this can also be constexpr.

2022-04-01 08:13 UTC, msimberg commented on libs/pika/version/src/version.cpp
> +        std::string version = pika::util::format("Version:\n"
Not for this PR, but I think with fmt/`std::format` we can also make these constexpr. And change the `ostringstream` ones to use `format` as well.

2022-04-01 14:58 UTC, msimberg commented
test cscs

2022-04-06 14:53 UTC, msimberg commented
test cscs

2022-04-06 20:40 UTC, aurianer commented
test cscs

2022-04-07 07:30 UTC, msimberg commented
bors merge

2022-04-07 07:53 UTC, merged