Clean up the timing module
pika-org/pika pull request #209
Opened 2022-04-27 13:41 UTC by aurianer

What I did for this cleanup is really minimal, feel free to comment if I'm missing anything

2022-04-28 10:42 UTC, msimberg reviewed
Thanks @aurianer. I'd like to see the `detail` namespace changes for sure in this PR, the rest you can choose if you want to do them here or in separate PRs.

2022-04-28 10:42 UTC, msimberg commented on libs/pika/timing/include/pika/timing/scoped_timer.hpp
>      struct scoped_timer
Could you check if this is used? And if it is I think it can go in `detail`?

2022-04-28 10:42 UTC, msimberg commented on libs/pika/timing/include/pika/timing/steady_clock.hpp
>      class steady_time_point
It feels like it should be possible to just use `steady_clock::time_point`, but then again there's probably a reason why this exists in the first place. If you don't mind, could you check if that would be possible? This is not a blocker for this PR.

2022-04-28 10:42 UTC, msimberg commented on libs/pika/timing/include/pika/timing/high_resolution_timer.hpp
> +namespace pika::chrono {
```suggestion
namespace pika::detail {
```

2022-04-28 10:42 UTC, msimberg commented on libs/pika/timing/include/pika/timing/high_resolution_clock.hpp
>      struct high_resolution_clock
Let's just use `std::chrono::high_resolution_clock` instead.

2022-07-05 13:24 UTC, aurianer commented
bors try

2022-07-05 15:17 UTC, msimberg requested changes
Apologies if some comments are no longer relevant, I made them before you pushed the latest commit.

2022-07-06 14:23 UTC, aurianer commented on libs/pika/execution/include/pika/execution/executors/auto_chunk_size.hpp
> +                    if (dur.count() != 0 && min_time_.count() >= dur.count())
yes I did it in `persistent_auto_chunk_size`, I don't know why not also here ^^' thanks!

2022-07-06 14:30 UTC, aurianer commented on libs/pika/timing/include/pika/timing/high_resolution_timer.hpp
> +        //constexpr high_resolution_timer(double t) noexcept
not used and now removed

2022-07-06 14:37 UTC, aurianer commented
bors try

2022-07-06 14:38 UTC, aurianer commented on libs/pika/runtime/src/runtime.cpp
>      std::uint64_t runtime::get_system_uptime()
yep already done :)

2022-07-06 15:35 UTC, aurianer commented
bors try

2022-07-07 14:29 UTC, msimberg approved these changes

2022-07-07 14:30 UTC, msimberg commented
You still need to fix the HIP failure, otherwise this is good to go.

2022-07-08 15:04 UTC, aurianer commented
should be solved now
bors try

2022-07-10 17:38 UTC, aurianer commented
bors try

2022-07-11 07:28 UTC, msimberg requested changes
Just one more change. I think this should be good to go after that.

2022-07-11 07:28 UTC, msimberg commented on libs/pika/async_cuda/tests/unit/cublas_matmul.cpp
> +    double us1 = t1.elapsed<microseconds>();
```suggestion
    double us1 = t1.elapsed<std::chrono::microseconds>();
```
and the same below.

2022-07-11 10:56 UTC, aurianer commented on libs/pika/async_cuda/tests/unit/cublas_matmul.cpp
> +    double us1 = t1.elapsed<microseconds>();
sorry overlooked

2022-07-11 11:16 UTC, msimberg commented
Actually, one more: https://app.circleci.com/pipelines/github/pika-org/pika/2019/workflows/06c49df1-253a-48b6-bdd8-9c08dabd0852/jobs/20191/steps?invite=true#step-102-100 in `mpi_ring_async_sender_receiver.cpp`.

2022-07-11 11:18 UTC, msimberg commented on libs/pika/async_cuda/tests/performance/cuda_scheduler_throughput.cpp
> +        pika::detail::high_resolution_timer t1;
```suggestion
        pika::chrono::detail::high_resolution_timer t1;
```

2022-07-11 13:15 UTC, msimberg commented
https://app.circleci.com/pipelines/github/pika-org/pika/2053/workflows/0ec8e656-f130-4df5-9eef-7d971c3d9dc0/jobs/20484/steps?invite=true#step-102-105

2022-07-11 14:54 UTC, aurianer commented
bors try

2022-07-12 10:41 UTC, msimberg commented
The remaining failures are unrelated.

bors merge

2022-07-12 11:42 UTC, msimberg approved these changes

2022-07-12 11:42 UTC, msimberg commented
bors merge

2022-07-12 12:16 UTC, merged