Stringformat
pika-org/pika pull request #601
Opened 2023-02-17 14:00 UTC by biddisco

Rejoin broken strings and then reapply clang-format to improve string layout

2023-02-17 15:36 UTC, msimberg requested changes
Thanks @biddisco. This is really nice.

Could you please update this to use the new formatting script: https://github.com/pika-org/pika-algorithms/blob/3e4ea7cd7f5eec8eb9c462beae0076c550aa0151/.circleci/config.yml#L104?

2023-02-17 15:36 UTC, msimberg commented on tools/string-join.awk
> +# Copyright (c) 2019 The STE||AR-Group
```suggestion
# Copyright (c) 2023 ETH Zurich
```
Maybe also on the formatting script.

2023-02-17 15:36 UTC, msimberg commented on tools/string-join.awk
> +# if we see "clang-forma on" turn back on processing
```suggestion
# if we see "clang-format on" turn back on processing
```

2023-02-17 15:36 UTC, msimberg commented on tools/string-join.sh
> +    awk -f $awkscript ${file} >${tmpfile}
```suggestion
    awk -f "$awkscript" "${file}" >"${tmpfile}"
```
and the same for the other codacy suggestions below (it's all about double-quoting variables).

2023-02-19 08:41 UTC, biddisco commented
> Thanks @biddisco. This is really nice.
> 
> Could you please update this to use the new formatting script: https://github.com/pika-org/pika-algorithms/blob/3e4ea7cd7f5eec8eb9c462beae0076c550aa0151/.circleci/config.yml#L104?

I don't quite understand what you're asking - are you saying that the default clang-format check should also run the string rejoin script too? - or are you asking for a change to the too/script to use something else?

2023-02-20 09:00 UTC, msimberg commented
> I don't quite understand what you're asking - are you saying that the default clang-format check should also run the string rejoin script too? - or are you asking for a change to the tool/script to use something else?

The first. The only way we're going to _consistently_ remember to use the string-joining script is by enforcing it in CI. Otherwise it's only going to applied every now and then whenever someone remembers.

2023-02-21 11:20 UTC, biddisco commented
> > The first. The only way we're going to consistently remember to use the string-joining script is by enforcing it in CI. Otherwise it's only going to applied every now and then whenever someone remembers.
> 
> For what I understood the string joining was a one time thing. With the fact that we now allow the line length to be 100, the strings will most likely not be broken into multiple lines no? @biddisco correct me if I'm wrong

Yes, the string join could be run every time, but it is really only needed after a change in something like clang-format rules. It might smarten up some code that has strings when added but I don't think it needs to be run always.

I'd be fine with merging 'as is' (if you'e happy) and leaving it out of CI for the time being - there is one outstanding corner case with strings that could cause a fail (and then every commit would trigger it in CI) that needs to be fixed - then it could be added painlessly to CI.

2023-02-21 11:26 UTC, msimberg commented
Ok, thanks @aurianer and @biddisco for the comments. Let's leave it out for now then. I would prefer it to be in CI eventually, but if you're not completely happy with it yet let's leave that for another day.

2023-02-21 11:27 UTC, msimberg approved these changes

2023-02-21 11:28 UTC, msimberg commented
Merging manually as CI is not running at the moment.

2023-02-21 11:28 UTC, merged