Cuda polling
pika-org/pika pull request #609
Opened 2023-02-23 08:51 UTC by biddisco

Redesign the way polling for cuda events is handled

Cuda events are polled (by any thread on the pool on which polling is enabled) and passed to a lockfree queue when ready. The polling loop first checks ready events and invokes callbacks, and only then takes the lock and checks outstanding events which are placed on the ready queue. 
This means that as soon as events are ready, any thread can invoke the callback - a single polling thread can find N events are ready and place them in the ready queue and N other threads can start handling the completions - instead of only allowing the polling thread to handle them.

The locking and completion handling has been reworked significantly and gives much better results.

2023-02-23 11:01 UTC, msimberg requested changes

2023-02-23 11:01 UTC, msimberg commented
bors try

2023-02-23 12:34 UTC, biddisco commented on libs/pika/async_cuda/include/pika/async_cuda/cuda_polling_helper.hpp
> +                set_pool_name("default");
grrrr. I thought I had already done that everywhere. I missed one it seems. I might have pushed the wrong version. I will check.

2023-03-07 08:58 UTC, msimberg approved these changes

2023-03-07 15:15 UTC, msimberg commented
bors try

2023-03-08 08:46 UTC, msimberg commented
bors merge

2023-03-08 09:42 UTC, merged